---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: docker-cleaner
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: docker-cleaner
  template:
    metadata:
      labels:
        app: docker-cleaner
    spec:
      volumes:
        - name: dockersocket
          hostPath:
            path: /var/run/docker.sock
      containers:
      - name: docker-cleaner
        image: bywang/docker-cleaner
        imagePullPolicy: Always
        env:
        - name: CLEAN_INTERVAL
          value: "{{ .Values.dockerCleaner.clean_interval }}"
        - name: CLEAN_FILTER
          value: {{ .Values.dockerCleaner.clean_filter }}
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock