replicas: 3

image:
  repository: microsoft/vsts-agent
  tag: ubuntu-16.04-docker-18.06.1-ce-standard
  pullPolicy: Always

resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 500m
    memory: 1Gi
  disk: "50Gi"
  storageclass: "managed-premium"

cleanRun: false

volumeMounts:
- name: docker-socket
  mountPath: /var/run/docker.sock
  readOnly: false

volumes:
- name: docker-socket
  hostPath:
    path: /var/run/docker.sock

extraEnv: {}

extraContainers: []
